### PR TITLE
Eclipse Scout SDK 13.0.23 for SimRel 2023-12 M1 with Scout RT 23.2.5

### PR DESCRIPTION
**Pull request by avandorp**

### CODE REVIEW

**Comment by merks** [comment]
I think I'm really going to need to block people creating branches in the repository rather than in their own fork because this approach kicks off to build, which is not desired...

**Comment by avandorp** [comment]
> I think I'm really going to need to block people creating branches in the repository rather than in their own fork because this approach kicks off to build, which is not desired...

Sorry about that. That's our usual workflow (and the easiest from within Eclipse?) for changes from within the team. I will delete the branch once merged.

**Comment by merks** [comment]
It's really not a big problem, and maybe not even a problem if it didn't kick off two builds  and as long as folks delete the branches.  👍

**Comment by jonahgraham** [comment]
> It's really not a big problem, and maybe not even a problem if it didn't kick off two builds and as long as folks delete the branches. 👍

I *think* you can change "Filter by name (with regular expression)" in https://ci.eclipse.org/simrel/job/simrel.build/configure to `main` and then only the `main` branch and PRs will build. You can also make it `(main|.*_maintenance)` to only build main and maintenance branches (assuming we ever have one again in the future.

**Comment by merks** [comment]
I think it has to be like `(main|.*_maintenance|PR-.*)` otherwise I don't think the PR builds were started...

**Pull request merged**
