### PR TITLE
Update TM4E to 0.9.0

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by merks** [comment]
Cool, these are the only things that use the older guava version:

image

Thanks. 😀

**Comment by cdietrich** [comment]
@merks unfortunately i cant really work on it on lsp4j side. dont know if @jonahgraham has any capacity left. see https://github.com/eclipse-lsp4j/lsp4j/tree/cd_widenGuava

**Comment by merks** [comment]
I was just this second looking if there is an Oomph setup but there is not.  It looks like the build uses gradle (which is  something I just don't want to learn).  What a nightmare.

**Comment by jonahgraham** [comment]
I'll try to get LSP4J done today.

**Comment by merks** [comment]
I created this PR to move things along more quickly, hopefully:

https://github.com/eclipse-lsp4j/lsp4j/pull/782

**Pull request merged**
