### PR TITLE
Simrel updates for Eclipse and Equinox for 2023-12 M1

### PR DESCRIPTION
**Pull request by MohananRahul**
Simrel updates for Eclipse and Equinox for 4.30 (2023-12) M1

### CODE REVIEW

**Comment by MohananRahul** [comment]
@merks Please review

**Comment by merks** [comment]
It looks like GEF is relying on something the platform previously provided but that it no longer provides because it's using newer simplified dependencies.  I'll need to find a workaround...

Just leave it with me and I will merge when I'm doing later today or early tomorrow.

**Comment by azoitl** [comment]
> It looks like GEF is relying on something the platform previously provided but that it no longer provides because it's using newer simplified dependencies. I'll need to find a workaround...
> 
> Just leave it with me and I will merge when I'm doing later today or early tomorrow.

From what I see it is GMF or did I miss something?

**Comment by merks** [comment]
Sorry, you're right. It's these two things that are missing requirements (because of bundle requirements) that they formerly got from the Platform:

image

**Comment by merks** [comment]
Sorry, I forgot how one can add changes to this pull request.  I ended up opening a new one:

https://github.com/eclipse-simrel/simrel.build/pull/11

**Comment by merks** [comment]
The other PR went through...

**Pull request closed without merging**
