### PR TITLE
Removed RedDeer from org.eclipse.simrel.build

### PR DESCRIPTION
**Pull request by olkornii**

### CODE REVIEW

**Comment by merks** [comment]
Do you think there is zero chance of someone else getting involved to help with builds and contributions?  If there is a chance, we could just disable it for now. 

Thanks for being proactive!

**Comment by merks** [comment]
Not that because of infrastructure problems the verification job has not kicked in so please hold off.

**Comment by olkornii** [comment]
@merks I still hope that someone will take care of it, but @akurtakov adviced to remove it from simrel.build. So I hope someone else might add it back.

**Comment by akurtakov** [comment]
So far, there is no indication of anyone being interested and I'm afraid that it gets disabled instead of removed it will stay as deadweight here as no one will come to remove it on purpose later. Adding it back on the other hand should be easy option - that's why I recommended removing.

**Comment by merks** [comment]
I’m fine with whatever you folks feel is best.

**Comment by olkornii** [comment]
@merks job failed due to "403 Forbidden": https://repo.eclipse.org/content/repositories/tycho-snapshots
some kind of outage?

**Comment by olkornii** [comment]
@merks looks good now. Thank you. What is the next step? Should I just merge?

**Comment by merks** [comment]
Yes it looks good now. You can squash and merge or rebase and merge now. 

Thank you too.

**Pull request merged**
