### PR TITLE
Contribute WTP 3.35 M3 for 2024-09

### PR DESCRIPTION
**Pull request by nitind**

### CODE REVIEW

**Comment by merks** [comment]
FYI, as a hack I added the Jetty repository including a single bundle from it, i.e,. the bundle that's missing from WTP's repository:

image

then aggregation works and I can check what is strictly requiring the commons-logging bundle which no longer is the case for WTP:

image

So this looks promising.  (Neither of those two features is installed in any EPP product.)

**Comment by nitind** [comment]
Adding [that jetty bundle](https://github.com/eclipse-servertools/servertools/commits/master/) doesn't result in a CI build that I can contribute cleanly, but each time I fill a dependency the contribution fails over wanting yet another one added. This was the main reason the "plus" bundle was there in the first place. I can keep iterating, but something about this behavior is different from before.

**Comment by merks** [comment]
I suspect it's a combination of factors.    RAP requires strictly the 12.0.11 version:

image

Likely WTP was working when someone else contributed the jetty things transitively needed by WTP.  But because the other contributions are at 12.0.11, something is now missing.   

Note that the platform just contributed m3 so if you rebase, maybe the problem clears up?

**Comment by merks** [comment]
I locally did a pull, disabled my jetty repository hack and then aggregation works.  So yes, please rebase your PR so that it's on top of the platform's M3 contribution.

**Comment by merks** [comment]
Yeah!  🥳

**Comment by merks** [comment]
So, lesson learned: if there is a new version of Jetty, contribute WTP after the Platform contributes its milestone.

**Pull request merged**
