### PR TITLE
[modisco] 1.5.5 for 2024-09

### PR DESCRIPTION
**Pull request by ewillink**

### CODE REVIEW

**Comment by merks** [comment]
FYI, it's convenient to enable this so that when the validation is successful the PR is automatically rebased an merged?

image

**Comment by ewillink** [comment]
> the PR is automatically rebased an merged
That looks really handy, but where is it? Perhaps you have more privileges.

**Comment by merks** [comment]
It's described here with screen captures about how it should look:

https://github.com/orgs/eclipse-simrel/discussions/3#discussioncomment-8111319

**Comment by merks** [comment]
To what does #4156 refer?  The auto merge option appears with 30 seconds of creating the PR.    Anyway, if something isn't working just for you, there isn't much I can personally do about it.  One would need to work with the helpdesk for that.  In any case, the other folks whom I pinged to remind them this was possible are generally using it after the reminder; I see that because I get an email as soon as a PR is opened....

**Comment by ewillink** [comment]
#4156. Oops I assumed the wrong bugspace. We do not have an Eclipse-wide bug-space like Bugzilla and my request to define a standard such as #EFH4176 has yet to progress. Maybe I was looking for automerge too late.

**Pull request merged**
