### PR TITLE
SWTBot contribution for 2024-06 RC1

### PR DESCRIPTION
**Pull request by PatrickTasse**

### CODE REVIEW

**Comment by merks** [comment]
I’ve never seen that before 

image

**Comment by PatrickTasse** [comment]
Did a Squash and merge.

**Comment by PatrickTasse** [comment]
github gonna github

**Comment by merks** [comment]
Maybe you branched from your fork’s main branch and it’s badly out of sync with the actual repository?  You can only fix that via the web view of your fork…

**Pull request merged**
