### PR TITLE
Explicitly exclude org.apache.commons.logging 1.2.0.v20180409-1502

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-orbit/orbit-simrel/issues/40

### CODE REVIEW

**Comment by cdietrich** [comment]
hmmmm i wonder if this will break mwe/xtext
(build.properties in new xtext project)

**Comment by merks** [comment]
> hmmmm i wonder if this will break mwe/xtext (build.properties in new xtext project)

Why would it?  I don't see versions mentioned:

image

I don't see that qualifier mentioned anywhere:

image

And the 1.2.0 version will be present instead.

**Comment by cdietrich** [comment]
so there still be be apache.commons.logging 1.2.0
and not apache.commons.commons-logging 1.3.3
?

**Comment by merks** [comment]
Yes.

**Pull request merged**
