### PR TITLE
Eclipse Mylyn (with Mylyn Docs) 4.2.0 M1+ for 2024-03 M1+

### PR DESCRIPTION
**Pull request by ruspl-afed**
https://download.eclipse.org/mylyn/updates/milestone/S202401111924

### CODE REVIEW

**Comment by jonahgraham** [comment]
@ruspl-afed  The CI is failing (as you probably noticed) let me/us know if you want us to look at anything

**Comment by ruspl-afed** [comment]
Yes, I need to deliver org.jsoup

**Comment by jonahgraham** [comment]
Once these renamed bundles make it all the way through the pipelines to an EPP output I can test that it is all put together as expected. I expect the EPP build will fail due to the feature name change and I will fix that tomorrow(ish).

**Review by jonahgraham — APPROVED** [review]
This looks fine to me - you can merge now and we'll have a CI build in a few hours.

The yet to be announced 2024-03 M1 will not contain this change as it has already been built.

**Pull request merged**
