### PR TITLE
Contribute TM 4.700 for M2

### PR DESCRIPTION
**Pull request by sbouchet**
https://download.eclipse.org/tm/updates/4.5.700-SNAPSHOT/repository/

### CODE REVIEW

**Comment by sbouchet** [comment]
see #438

**Comment by merks** [comment]
@sbouchet 

I strongly suggest you rename your release record 4.700 to 4.5.700 to prevent future confusion:

https://projects.eclipse.org/projects/tools.tm/releases/4.700

I made a mistake like this with EMF one time and was happy that it's possible to rename the record...

**Comment by sbouchet** [comment]
@merks : very good catch. it is indeed a typo that can be easily fixed :)

**Comment by sbouchet** [comment]
release record fixed https://projects.eclipse.org/projects/tools.tm/releases/4.5.700

**Pull request merged**
