### PR TITLE
Trace Compass contribution for 2023-12 M3

### PR DESCRIPTION
**Pull request by PatrickTasse**
Change-Id: Ica89157aa113dd063883a5777600c06a1b8eaf5d

### CODE REVIEW

**Comment by PatrickTasse** [comment]
I'm not sure I understand the build error:

Missing requirement: Zephyr support core 2.5.4.202210011055 (org.eclipse.rcptt.zephyr 2.5.4.202210011055) requires 'osgi.bundle; org.apache.commons.lang3 0.0.0' but it could not be found

We have org.apache.commons.lang3 in our targets, taken from the orbit-aggregation repository.

Also, I'm sorry if I missed it, but I read the following issue
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3624
and I'm not sure what's the procedure to get these PRs merged for a simrel milestone, do we just create the PR and a simrel committer will pick it up, or do we need to notify somehow? (I understand that maybe this one didn't get picked up simply because it failed the build).

**Comment by merks** [comment]
Everyone who had permissions should be been added as committers to the project, but I don't see you listed here:

https://projects.eclipse.org/projects/technology.simrel/who

Please subscribe to the project mailing list:

https://accounts.eclipse.org/mailing-list/simrel-dev

I started this election:

https://projects.eclipse.org/projects/technology.simrel/elections/election-patrick-tasse-committer-eclipse-simrel

Detailed contribution instructions are here:

https://github.com/orgs/eclipse-simrel/discussions/3

(Change IDs are no longer needed).

Your new contributed update site does not contain org.apache.commons.lang3. 

image

But your old one did:

image

If you removed includes from your features, that's great, but you still need to take steps to ensure these things end up in your update site by include then in a "dependencies" feature that's included in the category.xml or directly include them in the category.xml...

I can help merge your contribution until you have permission to do it yourself.  I did notice the PR earlier today, but given it's broken, I took no action.  If there's anything else I can do to help, just ask.

**Comment by merks** [comment]
Oh, and don't wait for m3 to contribute.   Let's do it as soon as the validation passes.

**Comment by PatrickTasse** [comment]
Thank you Ed!

Indeed I had removed all these 3rd party plugins from the update site, for other reasons [*]. I wasn't sure why they were needed originally, or if they were still needed, so I had tried to install our features from this update site over a vanilla Eclipse IDE, and it worked.

Now after some testing, I realize that it works because the IDE has the Eclipse release update site configured by default, and it seems to contain all the plugins that we need. If I disable it, then install fails unless I add back all these 3rd party plugins to our update site. But I also need to add many more plugins than the original list (basically all the non-platform plugins from other Eclipse simrel projects that we depend on).

That makes me believe that the simrel build job uses another update site or set of update sites to validate the contributions, do you know what it is so that we could use it to test our update site before creating our milestone build?

[*] The reason I tried to remove the 3rd party plugins is because some bundles were renamed in the orbit-aggregation repository. We have been building our project against many target platforms (currently down to 2021-06 4.20) using the same source code. In 2023-09 we avoided the issue of renamed bundles by getting the bundles with their old name from an older Orbit site in our target. But now in 2023-12 we are trying to do the right thing by getting all 3rd party bundles from the latest orbit-aggregation repository and suffering the consequences of the renamed bundles, e.g. having different versions of tracing.product and RCP feature.xml files depending on target, and overwriting those files in a special pre-build step. So we might have to add our update site category.xml to this list of multi-version files.

**Comment by merks** [comment]
The CBI p2 aggregator uses the p2 planner as if it were creating an installation that requires all bundles and all features specified in all Contributions. It uses all update sites of all Contributions to compute all the bundles and features that satisfy the transitive requirements of the explicitly included bundles and features.  No Orbit site is is contributed to SimRel so nothing will automatically come from Orbit.   So yes, if you have a dependency on another project, that project's 3rd party dependencies are likely/hopefully in their p2 repository, including in one they contribute to SimRel.   So in that case, you could overlook adding it to your own repository. 

To test what SimRel is doing, you could take a plain-old Eclipse SDK, add the update sites contributed by your SimRel dependencies, and then try to install all the features from your update site.  Having dependencies on other projects makes the problem more difficult because it's harder to determine which 3rd party bundles you need directly and which ones are needed by your dependencies and hence are most likely provided by the update sites of your dependencies.

Of course you can also just use the aggregator for doing that validation as described here:

https://github.com/orgs/eclipse-simrel/discussions/3

That's generally what I do.  I.e., I do a local Tycho build, change my *.aggrcon to reference the local update site (file:), validate, and the update my dependencies feature to include what's missing. Then rinse, lather, repeat...

**Pull request merged**
