### PR TITLE
Update TM4E to 0.10.0

### PR DESCRIPTION
**Pull request by sebthom**
see https://github.com/eclipse/tm4e/releases/tag/0.10.0

### CODE REVIEW

**Comment by sebthom** [comment]
@akurtakov can you please help me out? I have no idea what the Jenkins build error is trying to tell me.

**Comment by akurtakov** [comment]
I get the same error when validate aggregation locally and honestly this is beyond me. I'll have to defer to @merks  for that one.

**Comment by merks** [comment]
I’ll be home in a few minutes. My guess at a glance is that someone is editing the xml directly rather than using the editor.

**Comment by akurtakov** [comment]
Would you please add readme.md to the repo stating what should be used for editing and how to get it (plain p2 url link too for people having their "pet" IDEs)?

**Comment by akurtakov** [comment]
Thanks @sebthom for figuring it out!

**Comment by merks** [comment]
There are a bunch of "root files" missing that I need to add to the repo and a bunch of documentation that needs to be migrated from the wiki.  Unfortunately what I don't have is a bunch of prioritized time for that.  😱 

I'm also not inclined to provide setup instructions so that people can do things manually in their pet installations because such instructions tend to become outdated, the instructions might not actually work in their pet installation version, and people tend not to actually read much of anything and tend to make mistakes when they follow instructions like a monkey.

**Pull request merged**
