### PR TITLE
Upgrade WildWebDeveloper to v.1.3.1

### PR DESCRIPTION
**Pull request by vrubezhny**

### CODE REVIEW

**Comment by merks** [comment]
If you need help merging just let me know.

**Comment by vrubezhny** [comment]
> If you need help merging just let me know.

I expect to have enough rights to be able to merge the PR.

**Comment by vrubezhny** [comment]
@merks But yeah... A question appeared... I just received a message like: 

```
FAILED: Job 'simrel.oomph.repository-analyzer.test [2024]': Check console output at https://ci.eclipse.org/simrel/job/simrel.oomph.repository-analyzer.test/2024/
```

Should I do anything regarding this?

**Comment by merks** [comment]
Don’t worry.  It’s an annoying problem that the server returns stale metadata that doesn’t correspond to the actual artifacts present.  I need to add some longer delay.  Only the verification build really matters. Thanks for asking though.

**Pull request merged**
