### PR TITLE
DO NOT MERGE test with Xtext nightly without xpand dep to see what explodes DO NOT MERGE 

### PR DESCRIPTION
**Pull request by cdietrich**
DO NOT MERGE

### CODE REVIEW

**Comment by merks** [comment]
Note that you can do the validation locally as described here:

https://github.com/orgs/eclipse-simrel/discussions/3

**Comment by cdietrich** [comment]
am not sure if my netbook can handle it.

**Comment by merks** [comment]
I think it will be better to disable the feature rather than delete it so that it's easier to enable later rather than have to add it and add it to the right category again...

**Comment by merks** [comment]
Note that validation just does a p2 resolve, it doesn't download any artifacts...

**Pull request closed without merging**
