### PR TITLE
Update to MAT 1.15.0 for 2023-12 M1

### PR DESCRIPTION
**Pull request by ajohnson1**
First version of MAT 1.15.0

### CODE REVIEW

**Comment by ajohnson1** [comment]
@krumts Are you happy for this first version of 1.15.0 to go into SimRel 2023-12 M1 (built today/tomorrow?) ?
I can't merge it myself.

**Comment by merks** [comment]
@ajohnson1 

Were you previously able to merge with Gerrit?  I.e., is this a permissions problem new to GitHub?

**Comment by ajohnson1** [comment]
I get:
>This branch has no conflicts with the base branch
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

I don't think I have merged before, although I have made changes which I think someone else merged.
https://github.com/eclipse-simrel/simrel.build/commits/main/mat.aggrcon
says I committed changes - but that might not be the same as merged.

Krum is the project lead on MAT, I'm a committer, so I think he could do the merge. Do all committers normally have permission for SimRel - or is that for project leads?

**Comment by merks** [comment]
I think in the past someone just asked for permission and were given permission with no special status required, other than that one is participating in SimRel and needs the rights to make the contributions.  I guess now with it becoming a project, maybe an election is needed, but that will be a PITA so I hope not.  In any case, of course I can merge this for you too...

**Comment by ajohnson1** [comment]
@merks - Yes, please, do the merge for me.
I don't need authorization to change *anything* in simrel.build, but it would be convenient if Krum or I could change mat.aggrcon in the future.

Otherwise, perhaps one way to manage authorization would be to allow if the requestor is in the *old* contacts section. Although the contacts section is validated and only allows users from a list, and I'm not on that list.

**Comment by merks** [comment]
We will need to iron out permissions issues/process when this step is complete:

https://projects.eclipse.org/proposals/eclipse-simrel

I really prefer there not to be elections because that will just cause delays and then most people won't vote...

**Pull request merged**
