### PR TITLE
embedcdt: update for 6.6.0

### PR DESCRIPTION
**Pull request by ilg-ul**

### CODE REVIEW

**Comment by merks** [comment]
I’m confused. Why are there 7 commits in the PR?

Could you please rebase on main with a single commit?

**Comment by ilg-ul** [comment]
I'm even more confused, due to the absurd restrictions Eclipse imposes, I ended up with multiple forks of simrel in various organisations and inevitably I messed the commits :-(

**Comment by merks** [comment]
Have you created an ide using the link here?

https://github.com/eclipse-simrel#creating-an-eclipse-development-environment

I don’t think you would commit broken p2 sites if you used the available tools that allow you to verify your contribution before you commit it. 

You may wish to review the instructions for the recommended workflow 

https://github.com/orgs/eclipse-simrel/discussions/3

I’m not aware of any absurd restrictions. Can you elaborate?

**Comment by ilg-ul** [comment]
> I’m not aware of any absurd restrictions. Can you elaborate?

For example how can I create new projects/forks in eclipse-embed-cdt? I don't see the Settings menu.

Screenshot 2024-04-03 at 22 32 09

This is how I ended up with multiple forks in different other organizations.

Or how can I configure the links to the project web? Or other organization profile details?

**Comment by merks** [comment]
I hesitate to ask how forks of eclipse-embed-cdt relate to this simrel contribution. Please open a helpdesk issue if something isn’t working properly.  Link it here so I can track what is wrong.  As I understand it, you can use otterdog to configure your organization. It posted details on cross-projects last year. 

Meanwhile, setting up an ide and reading the recommended workflow is advised.

**Comment by ilg-ul** [comment]
> I hesitate to ask how forks of eclipse-embed-cdt relate to this simrel contribution.

I had a fork of simrel.build in eclipse-embed-cdt. Due to a mistake, I messed the commits history, and I decided to recreate the fork. I was able to remove the fork repo, but when I tried to create it again, the eclipse-embed-cdt organisation was greyed in the list (insufficient permission), so I used my user organisation. This was some time ago, and I forgot about it. For the new 6.6.0 release I created another fork of simrel in the embed-cdt organisation, but I did not update the local repo origins properly, and I ended up trying to sync commits between multiple repos.

If this PR passes, I'll remove all these forks and hopefully clean up the mess.

**Comment by jonahgraham** [comment]
I agree that this change looks fine to me - the state of your forks doesn't really matter and I am sure once you delete the extraneous ones it will be clear for the future.

The extra commits in this PR are ugly, but as it was merged with a squash it doesn't affect anything AFAICT as the main branch has a clean history.

**Comment by ilg-ul** [comment]
I removed all forks, we should be clear now.

During the previous 6.5.0 release, when I asked Jonah why the old workflow is no longer functional, he mentioned something about a new workflow, but it was not ready and he suggested to update the repo manually.

Next time I'll try to use the new workflow, as documented.

**Comment by ilg-ul** [comment]
@jonahgraham, if the new workflow requires a simrel fork, please create one in eclipse-embed-cdt, since I don't have rights to do it.

**Comment by jonahgraham** [comment]
Please create forks in your personal name. But a fork isn't required, as a committer you can push directly to a branch - which has the advantage that if you do auto-merge the branch will be auto-deleted.

**Comment by merks** [comment]
One can auto-merge and auto-delete from your fork.   I very much prefer folks use a fork.  The auto-delete for a fork needs to be enabled in the fork's settings:

image

I generally have been enabling this for every fork I have because it works for both manual-merge and auto-merge (and there is always a restore button after merging).

**Pull request merged**
