### PR TITLE
Contribute TM 4.5.600

### PR DESCRIPTION
**Pull request by sbouchet**
Change-Id: I80c2bd30c64c495ac6230ae3ed70977d14edda0e

### CODE REVIEW

**Comment by sbouchet** [comment]
@merks seems i can't merge automatically this contrib. do i need to do something ?

**Comment by merks** [comment]
It's hard to say now that all the reviews are done.  I guess you looked at this:

https://github.com/orgs/eclipse-simrel/discussions/3#discussioncomment-8111319

I assume it looks like this for you now:

image

**Comment by sbouchet** [comment]
well... no, seems i don't have  write access.
Capture d’écran du 2024-01-16 16-35-53

**Comment by merks** [comment]
I’ll have to start an election.  I’ll try not to forget.

**Pull request merged**
