### PR TITLE
Xtext 2.36.0.M1 and MWE 2.19.0.M1 for Eclipse 2024-09 M1

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Comment by cdietrich** [comment]
@merks when and how are builds for PRs kicked off?

**Comment by merks** [comment]
@cdietrich 

The ci infrastructure has been a bit spotty/slow over the weekend.

**Comment by merks** [comment]
This page takes forever to come up


https://ci.eclipse.org/simrel/view/Releng%20jobs/job/simrel.build/job/PR-441/

It appears to be waiting for something:

image

**Comment by merks** [comment]
Okay, it finally started.   Patience is a virtue.  😈

**Comment by cdietrich** [comment]
@LorenzoBettini is it ok the disable parsley until you have a new version?
@ujhelyiz also VIATRA does not work anymore with new Xtext.
is it ok to also disable it?

@merks what is the general procedure in such cases?

**Comment by merks** [comment]
Nothing else is downstream from those two components.    What exactly is broken? Some junit4 xtext bundle has been removed?

**Comment by ujhelyiz** [comment]
> @LorenzoBettini is it ok the disable parsley until you have a new version?
> 
> @ujhelyiz also VIATRA does not work anymore with new Xtext.
> 
> is it ok to also disable it?
> 
> 
> 
> @merks what is the general procedure in such cases?

Feel free to disable VIATRA, I will check the problem in a few days.

**Comment by cdietrich** [comment]
yes. am not sure why they depend on a test feature/plugin

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini is it ok the disable parsley until you have a new version?

@cdietrich OK, please go on.

but what is the problem? I removed strict version ranges from Parsley.

**Comment by cdietrich** [comment]
it looks like parsley also depends on xtext.junit4

**Comment by merks** [comment]
This

image

versus this

image

**Comment by LorenzoBettini** [comment]
Yes, I'll fix that in Parsley; that's an unused old dependency that hasn't been used for a long time.
To think that I personally removed the old deprecated `junit` projects from the Xtext code base... ;)

**Comment by jonahgraham** [comment]
@LorenzoBettini are you likely to have an updated Parsley soon? I ask because [EPP for Modelling](https://github.com/eclipse-packaging/packages/blob/3fcbbfe79089d6377d0ffb22793dbe1792b36a25/packages/org.eclipse.epp.package.modeling.product/epp.product#L259) uses Parsley and the EPP builds are broken until either I remove (temporarily) Parsley from EPP, or I get an updated. Thanks for your input.

**Comment by LorenzoBettini** [comment]
@jonahgraham would the next week be OK?
Otherwise, I can try earlier but I'm a bit busy

**Comment by merks** [comment]
EPP can’t build without removing this from the product and then later adding it again. It’s a bit of a hassle.

**Comment by LorenzoBettini** [comment]
@merks so I should fix it ASAP, shouldn't I?
I'll try to do that tomorrow.
Sorry for the incovenience

**Comment by LorenzoBettini** [comment]
@jonahgraham I fixed Parsley, and re-enabled it in simrel.
This should fix EPP builds

**Comment by jonahgraham** [comment]
Thanks @LorenzoBettini  - the [build](https://ci.eclipse.org/packaging/job/epp/job/master/) looks good now.

**Pull request merged**
