### PR TITLE
Remove unused products removed from Eclipse-Platform

### PR DESCRIPTION
**Pull request by HannesWell**
Follow-up of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1235

### CODE REVIEW

**Comment by merks** [comment]
@HannesWell 

I assume you have sufficient permission that can merge this yourself, right?

**Comment by HannesWell** [comment]
> I assume you have sufficient permission that can merge this yourself, right?

Yes I do. Just wanted to give some time for comments. But since there were no objections in the initial PR and this is the logical consequence I assume its fine to submit this now.

Btw. it looks like that `Squash and Merge` is still suggested for this repo. Can you disable this?

**Comment by merks** [comment]
I always use squash and merge, even with all my platform contributions.

image

I thought one had to explicitly allow it:

https://github.com/eclipse-simrel/.eclipsefdn/blob/23d35310a8f4c9ad29cfcfa3bca55260ad155224/otterdog/eclipse-simrel.jsonnet#L33

**Comment by HannesWell** [comment]
Sorry when writing my remark about squash-and-merge I was actually focusing on something else and confused it with `Create a merge commit`.

> I always use squash and merge, even with all my platform contributions.

Personally I prefer `Rebased an merge`, because Squash and merge uses an artificial Github Commiter:
grafik

**Comment by merks** [comment]
Oh wow, you learn something new every day!

**Comment by jonahgraham** [comment]
I prefer rebase and merge when the sequence of commits is already what I want to submit, but squash and merge is very useful to rewrite history so that we don't have "fix review comments" type commits in main history.

**Comment by jonahgraham** [comment]
Thanks @HannesWell for pushing this through to completion.

**Comment by HannesWell** [comment]
Btw. I also tested locally that with the current 4.30 I-builds exactly those removed products were marked as missing.

> I prefer rebase and merge when the sequence of commits is already what I want to submit, but squash and merge is very useful to rewrite history so that we don't have "fix review comments" type commits in main history.

Yes I don't want to reflect the back and forth during development/review in the history, but I also don't like the Github-Committer and its mail (I somethimes even noticed that it uses a github-mail with a random number, which I assume is some sort of ID for my account). Therefore I usually do force-pushes and squash locally before doing the final submission.
If Squash-And-Merge would just use my Name and reqular mail address I would also use it.

**Pull request merged**
