### PR TITLE
Contribute WindowBuilder 1.14 M3 for Eclipse 2023-12

### PR DESCRIPTION
**Pull request by ptziegler**

### CODE REVIEW

**Comment by jonahgraham** [comment]
@ptziegler I retriggered in case it was a temporary/connectivity problem. If it fails again I am sure @merks will get back to you at some point. (FWIW EPP build also failed and is also rerunning now)

**Comment by merks** [comment]
That’s the second time today.

**Comment by ptziegler** [comment]
The second job seems to have been successful. Gave me a small shock when I first got the email. :sweat_smile:
Thanks for the response!

**Comment by merks** [comment]
It failed again this morning, twice in a row.  

What I could determine in this case is that there are failures like this:

> Retrying: /home/jenkins/agent/workspace/simrel.oomph.repository-analyzer.test/report/artifacts/plugins/com.mycorp.examples.timeservice.host.source_1.1.400.v20210403-2253.jar

Note in particular the 1.1.400.v20210403-2253 date.  The actual artifact available is this brand-new, just-contributed one:

[com.mycorp.examples.timeservice.host.source_1.1.400.v20231114-1017.jar](https://www.eclipse.org/downloads/download.php?file=/staging/2023-12/plugins/com.mycorp.examples.timeservice.host.source_1.1.400.v20231114-1017.jar)

So it appears that the server is serving stale metadata for some not-insignificant period of time:

image

I suppose we ought to add longer delays.  So annoying!

**Pull request merged**
