### PR TITLE
Contribute JGit/EGit 7.0.0.202407101547-m1 to 2024-09 M1

### PR DESCRIPTION
**Pull request by msohn**

### CODE REVIEW

**Comment by msohn** [comment]
missed to add new jetty bundle org.eclipse.jetty.ee10.servlet to egit p2 repo, fixed in https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1197538

**Comment by merks** [comment]
FYI, even if I add the jetty 12 update site, it then fails like this:

image

There are projects downstream from EGit so if you bump the major version you should assume that will likely have an impact.

**Comment by msohn** [comment]
you are right, doing this that late in the milestone isn't a good idea, will update egit early for the next milestone.

**Comment by merks** [comment]
I'll include a heads up in my email to SimRel.

**Comment by msohn** [comment]
thanks

To prepare consuming our major version bump consumers should bump the upper boundary of the version range for their jgit and egit dependencies to 8.0 or at least 7.1, e.g. from [6.10,7.0) to [6.0,7.1) or [6.10,8.0).

**Comment by merks** [comment]
Like I've done here:

https://github.com/eclipse-mylyn/org.eclipse.mylyn/commit/76cd0401249a57b112130a7149c4e27f4af64db0

I will test the combination of new EGit repo, with Jetty 12 repo that makes EGit happy and then with new Mylyn version which should accommodate new EGit version and see if there are any other problems so that we can iron them out long before m2.

**Comment by merks** [comment]
I tested this:

image

in combination with the mylyn latest night build:

image

That aggregates fine and then we have the lowest number of duplicate bundles ever:

image

So it looks like we'll be back on track for M1.

@ruspl-afed 

Would you mind if I produce another Mylyn milestone build immediately so that I can start preparations for m2 sooner rather than later? (I.e., as soon as EPP is done for M1.)

**Comment by msohn** [comment]
That would be great, let me know when this is available. 
Maybe I can contribute a first 7.0 version for m2 before leaving for vacation next Monday.

**Comment by merks** [comment]
@msohn 

I've updated Mylyn and contributed your m1 along with the jetty repository needed for your contribution to resolve.

Please, for your next contribution, when the EGit repository contains all the Jetty dependencies, delete the jetty repository from the EGit contribution:

https://github.com/eclipse-simrel/simrel.build/blob/59e9592f82dced802612938022df791a4c498b19/egit.aggrcon#L32-L34

**Pull request closed without merging**
