### PR TITLE
Contribute WindowBuilder 1.14 M2 for Eclipse 2023-12

### PR DESCRIPTION
**Pull request by ptziegler**

### CODE REVIEW

**Comment by merks** [comment]
@ptziegler 

I assume you are able to merge this yourself now...

**Comment by ptziegler** [comment]
@merks 
I don't think I do...
image

Do I have to create another HelpDesk issue for this or can you add me manually?

**Comment by merks** [comment]
It's a real project now so if you're not listed here:

https://projects.eclipse.org/projects/technology.simrel/who

we'd need to do an election and to do that I need the email address of your account...  Maybe you can send that to me via direct email?

**Comment by ptziegler** [comment]
I'm not in the list, so it seems like the election process should be the next step.
I've send you an email with my (and also containing) from the email-address that is linked to my Eclipse account.

**Pull request merged**
