### PR TITLE
Update TM4E to 0.10.3

### PR DESCRIPTION
**Pull request by sebthom**

### CODE REVIEW

**Comment by merks** [comment]
@sebthom I assume you are able to merge this yourself. 

You may wish to use auto merge in the future

https://github.com/orgs/eclipse-simrel/discussions/3#discussioncomment-8111319

**Comment by sebthom** [comment]
I have no permission to merge this PR.

**Comment by merks** [comment]
I lost track. I thought we did an election. If not, we should.

**Comment by merks** [comment]
FYI, I started an election:

https://projects.eclipse.org/projects/technology.simrel/elections/election-sebastian-thomschke-committer-eclipse-simrel

**Pull request merged**
