### PR TITLE
[MPC] MPC 1.11.0 contribution for 2024-09 M1

### PR DESCRIPTION
**Pull request by l3-g5**

### CODE REVIEW

**Review by merks — APPROVED** [review]
Awesome 😎

**Comment by merks** [comment]
It seems you should have done a pull before you created the pr.

**Comment by jonahgraham** [comment]
Thanks @l3-g5

**Comment by l3-g5** [comment]
> It seems you should have done a pull before you created the pr.

Yes, sorry, for forgetting the pull first. Squash and merge should clean up the mess in the history, right?

**Comment by merks** [comment]
You can try. It’s outside my comfort zone. 😱🤪

**Comment by l3-g5** [comment]
Yeah, worked as expected.

**Comment by merks** [comment]
FYI. When that staging build completes, I can test and confirm that the problem is fixed.  Thanks for your responsiveness.

**Pull request merged**
